name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd pipe && make
    - name: runServer
      run: cd pipe && ./server.out &
    - name: runClient
      run: cd pipe && ./client.out &
